## 怎样实现groupby分组统计

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(
    {
        'A':['foo','bar','foo','bar','foo','bar','foo','foo'],
        'B':['one','one','two','three','two','two','one','three'],
        'C':np.random.randn(8),
        'D':np.random.randn(8)
    }
)
df

     A      B         C         D
0  foo    one  2.313229 -0.515259
1  bar    one -1.892509 -0.773251
2  foo    two -1.358201 -0.210469
3  bar  three  0.459207  0.051755
4  foo    two  0.691635  2.245626
5  bar    two -2.383178  0.942217
6  foo    one -1.238536 -1.361242
7  foo  three -1.107660  0.242465

**一、分组使用聚合函数做数据统计**

1、单个列groupby,查询所有数据列的统计

In [4]:
df.groupby('A').sum()

            C         D
A
bar -3.816481  0.220721
foo -0.699533  0.401121

我们看到:\
1.groupby中的'A'变成了数据的索引列\
2.因为要统计sum,但B列不是数字,所以被自动忽略掉

2、多个列groupby,查询所有数据列统计

In [5]:
df.groupby(['A','B']).mean()

                  C         D
A   B
bar one   -1.892509 -0.773251
    three  0.459207  0.051755
    two   -2.383178  0.942217
foo one    0.537347 -0.938251
    three -1.107660  0.242465
    two   -0.333283  1.017579

我们看到:('A','B')成对变成了二级索引

In [6]:
df.groupby(['A','B'],as_index=False).mean()## 使用as_index=False让A和B两列不变成索引

     A      B         C         D
0  bar    one -1.892509 -0.773251
1  bar  three  0.459207  0.051755
2  bar    two -2.383178  0.942217
3  foo    one  0.537347 -0.938251
4  foo  three -1.107660  0.242465
5  foo    two -0.333283  1.017579

3、同时查看多种数据统计

In [7]:
df.groupby('A').agg([np.sum,np.mean,np.std])

            C                             D
          sum      mean       std       sum      mean       std
A
bar -3.816481 -1.272160  1.519346  0.220721  0.073574  0.857942
foo -0.699533 -0.139907  1.607569  0.401121  0.080224  1.344639

我们看到列变成了多级索引

4、查看单列的结果数据统计

In [8]:
# 方法一: 预处理，性能更好
df.groupby('A')['C'].agg([np.sum,np.mean,np.std])## 取出'C'这一列

          sum      mean       std
A
bar -3.816481 -1.272160  1.519346
foo -0.699533 -0.139907  1.607569

In [ ]:
# 方法二