## 分层索引MultiIndex

* 分层索引:在一个轴向上拥有多个索引层级,可以表达更高维度数据的形式;
* 可以更方便的进行数据筛选,如果有序则性能更好;
* groupby等操作的结果,如果是多key,结果是分层索引,需要会使用
* 一般不需要自己创建分层索引(MultiIndex有构造函数但一般不用)

In [2]:
import pandas as pd

In [3]:
stocks = pd.read_excel('./The Company Stocks.xlsx',engine='openpyxl')

In [7]:
stocks

           日期    公司     收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
0  2023-05-25    JD  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN
1  2023-05-24    JD  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
2  2023-05-23    JD  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
3  2023-05-22    JD  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
4  2023-05-19    JD  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN
5  2023-05-25  BABA  79.88  80.43  80.66  79.81   4.20 -0.0164         NaN
6  2023-05-24  BABA  81.21  82.17  82.60  80.88  15.44 -0.0201         NaN
7  2023-05-23  BABA  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
8  2023-05-22  BABA  86.10  85.67  87.48  85.65  15.11  0.0252         NaN
9  2023-05-19  BABA  83.98  83.85  85.20  83.48  21.57 -0.0209         NaN
10 2023-05-25    IQ   4.51   4.57   4.62   4.50   1.05 -0.0259         NaN
11 2023-05-24    IQ   4.63   4.70   4.72   4.40  14.19 -0.0211         NaN
12 2023-05-23    IQ   4.73   4.78   4.90   4.66  11.15 -0.0386         NaN
13 2023-05-22    IQ   4.92   5.07   5.27   4.91  13.76 -0.0081         NaN
14 2023-05-19    IQ   4.96   5.19   5.19   4.92  15.84 -0.0534         NaN

In [5]:
stocks.head()

          日期  公司     收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
0 2023-05-25  JD  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN
1 2023-05-24  JD  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
2 2023-05-23  JD  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
3 2023-05-22  JD  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
4 2023-05-19  JD  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN

In [6]:
stocks['公司'].unique()

array(['JD', 'BABA', 'IQ'], dtype=object)

In [7]:
stocks.index

RangeIndex(start=0, stop=15, step=1)

In [9]:
ser = stocks.groupby(['公司'])['收盘'].mean()
ser

公司
BABA    82.810
IQ       4.750
JD      34.604
Name: 收盘, dtype: float64

## 一、Series的分层索引MultiIndex

In [10]:
ser = stocks.groupby(['公司','日期'])['收盘'].mean()
ser

公司    日期
BABA  2023-05-19    83.98
      2023-05-22    86.10
      2023-05-23    82.88
      2023-05-24    81.21
      2023-05-25    79.88
IQ    2023-05-19     4.96
      2023-05-22     4.92
      2023-05-23     4.73
      2023-05-24     4.63
      2023-05-25     4.51
JD    2023-05-19    35.06
      2023-05-22    35.99
      2023-05-23    35.04
      2023-05-24    33.88
      2023-05-25    33.05
Name: 收盘, dtype: float64

多维索引中,空白的意思:使用上面的值

In [11]:
ser.index

MultiIndex([('BABA', '2023-05-19'),
            ('BABA', '2023-05-22'),
            ('BABA', '2023-05-23'),
            ('BABA', '2023-05-24'),
            ('BABA', '2023-05-25'),
            (  'IQ', '2023-05-19'),
            (  'IQ', '2023-05-22'),
            (  'IQ', '2023-05-23'),
            (  'IQ', '2023-05-24'),
            (  'IQ', '2023-05-25'),
            (  'JD', '2023-05-19'),
            (  'JD', '2023-05-22'),
            (  'JD', '2023-05-23'),
            (  'JD', '2023-05-24'),
            (  'JD', '2023-05-25')],
           names=['公司', '日期'])

In [12]:
# unstack把二级索引变成列
ser.unstack()

日期    2023-05-19  2023-05-22  2023-05-23  2023-05-24  2023-05-25
公司
BABA       83.98       86.10       82.88       81.21       79.88
IQ          4.96        4.92        4.73        4.63        4.51
JD         35.06       35.99       35.04       33.88       33.05

## 二、Series多层索引MultiIndex

In [13]:
ser

公司    日期
BABA  2023-05-19    83.98
      2023-05-22    86.10
      2023-05-23    82.88
      2023-05-24    81.21
      2023-05-25    79.88
IQ    2023-05-19     4.96
      2023-05-22     4.92
      2023-05-23     4.73
      2023-05-24     4.63
      2023-05-25     4.51
JD    2023-05-19    35.06
      2023-05-22    35.99
      2023-05-23    35.04
      2023-05-24    33.88
      2023-05-25    33.05
Name: 收盘, dtype: float64

In [14]:
ser.reset_index()

      公司         日期     收盘
0   BABA 2023-05-19  83.98
1   BABA 2023-05-22  86.10
2   BABA 2023-05-23  82.88
3   BABA 2023-05-24  81.21
4   BABA 2023-05-25  79.88
5     IQ 2023-05-19   4.96
6     IQ 2023-05-22   4.92
7     IQ 2023-05-23   4.73
8     IQ 2023-05-24   4.63
9     IQ 2023-05-25   4.51
10    JD 2023-05-19  35.06
11    JD 2023-05-22  35.99
12    JD 2023-05-23  35.04
13    JD 2023-05-24  33.88
14    JD 2023-05-25  33.05

In [15]:
ser.loc['JD']

日期
2023-05-19    35.06
2023-05-22    35.99
2023-05-23    35.04
2023-05-24    33.88
2023-05-25    33.05
Name: 收盘, dtype: float64

In [16]:
# 多层索引,可以用元组的形式筛选
ser.loc[('JD','2023/5/23')]

35.04

In [17]:
ser.loc[:,'2023/5/23']

公司
BABA    82.88
IQ       4.73
JD      35.04
Name: 收盘, dtype: float64

## 三、DataFrame的多层索引MultiIndex

In [18]:
stocks.head()

          日期  公司     收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
0 2023-05-25  JD  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN
1 2023-05-24  JD  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
2 2023-05-23  JD  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
3 2023-05-22  JD  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
4 2023-05-19  JD  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN

In [19]:
stocks.set_index(['公司','日期'],inplace=True)
stocks

                    收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
公司   日期
JD   2023-05-25  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN
     2023-05-24  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
     2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
     2023-05-22  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
     2023-05-19  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN
BABA 2023-05-25  79.88  80.43  80.66  79.81   4.20 -0.0164         NaN
     2023-05-24  81.21  82.17  82.60  80.88  15.44 -0.0201         NaN
     2023-05-23  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
     2023-05-22  86.10  85.67  87.48  85.65  15.11  0.0252         NaN
     2023-05-19  83.98  83.85  85.20  83.48  21.57 -0.0209         NaN
IQ   2023-05-25   4.51   4.57   4.62   4.50   1.05 -0.0259         NaN
     2023-05-24   4.63   4.70   4.72   4.40  14.19 -0.0211         NaN
     2023-05-23   4.73   4.78   4.90   4.66  11.15 -0.0386         NaN
     2023-05-22   4.92   5.07   5.27   4.91  13.76 -0.0081         NaN
     2023-05-19   4.96   5.19   5.19   4.92  15.84 -0.0534         NaN

In [20]:
stocks.index

MultiIndex([(  'JD', '2023-05-25'),
            (  'JD', '2023-05-24'),
            (  'JD', '2023-05-23'),
            (  'JD', '2023-05-22'),
            (  'JD', '2023-05-19'),
            ('BABA', '2023-05-25'),
            ('BABA', '2023-05-24'),
            ('BABA', '2023-05-23'),
            ('BABA', '2023-05-22'),
            ('BABA', '2023-05-19'),
            (  'IQ', '2023-05-25'),
            (  'IQ', '2023-05-24'),
            (  'IQ', '2023-05-23'),
            (  'IQ', '2023-05-22'),
            (  'IQ', '2023-05-19')],
           names=['公司', '日期'])

## 四、DataFrame有多层索引MultiIndex怎样筛选数据

* 元组(key1,key2)代表多层筛选多层索引,其中key1是索引第一级,key2是第二级
* 列表[key1,key2]代表同一层级多个key,其中key1和key2是并列的同级索引

In [21]:
stocks.loc['JD']

               收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
日期
2023-05-25  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN
2023-05-24  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
2023-05-22  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
2023-05-19  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN

In [27]:
stocks = stocks.sort_index()
stocks

                    收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
公司   日期
BABA 2023-05-19  83.98  83.85  85.20  83.48  21.57 -0.0209         NaN
     2023-05-22  86.10  85.67  87.48  85.65  15.11  0.0252         NaN
     2023-05-23  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
     2023-05-24  81.21  82.17  82.60  80.88  15.44 -0.0201         NaN
     2023-05-25  79.88  80.43  80.66  79.81   4.20 -0.0164         NaN
IQ   2023-05-19   4.96   5.19   5.19   4.92  15.84 -0.0534         NaN
     2023-05-22   4.92   5.07   5.27   4.91  13.76 -0.0081         NaN
     2023-05-23   4.73   4.78   4.90   4.66  11.15 -0.0386         NaN
     2023-05-24   4.63   4.70   4.72   4.40  14.19 -0.0211         NaN
     2023-05-25   4.51   4.57   4.62   4.50   1.05 -0.0259         NaN
JD   2023-05-19  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN
     2023-05-22  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
     2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
     2023-05-24  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
     2023-05-25  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN

In [26]:
stocks.loc[('JD','2023-5-23'),:]

                  收盘    开盘     高      低   交易量     涨跌幅  Unnamed: 8
公司 日期
JD 2023-05-23  35.04  35.2  35.7  34.97  7.56 -0.0264         NaN

In [28]:
stocks.loc[['BABA','JD'],:]

                    收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
公司   日期
BABA 2023-05-19  83.98  83.85  85.20  83.48  21.57 -0.0209         NaN
     2023-05-22  86.10  85.67  87.48  85.65  15.11  0.0252         NaN
     2023-05-23  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
     2023-05-24  81.21  82.17  82.60  80.88  15.44 -0.0201         NaN
     2023-05-25  79.88  80.43  80.66  79.81   4.20 -0.0164         NaN
JD   2023-05-19  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN
     2023-05-22  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
     2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
     2023-05-24  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
     2023-05-25  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN

In [29]:
stocks.loc[(['BABA','JD'],'2023-5-23'),:]

                    收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
公司   日期
BABA 2023-05-23  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
JD   2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN

In [30]:
stocks.loc[(['BABA','JD'],'2023-5-23'),'收盘']

公司    日期
BABA  2023-05-23    82.88
JD    2023-05-23    35.04
Name: 收盘, dtype: float64

In [35]:
stocks.loc[('JD',['2023-5-19','2023-5-24']),'收盘']

公司  日期
JD  2023-05-19    35.06
    2023-05-24    33.88
Name: 收盘, dtype: float64

In [36]:
# slice(None)代表筛选这一索引的全部内容
stocks.loc[(slice(None),['2023-5-23','2023-5-19']),:]

                    收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
公司   日期
BABA 2023-05-19  83.98  83.85  85.20  83.48  21.57 -0.0209         NaN
     2023-05-23  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
IQ   2023-05-19   4.96   5.19   5.19   4.92  15.84 -0.0534         NaN
     2023-05-23   4.73   4.78   4.90   4.66  11.15 -0.0386         NaN
JD   2023-05-19  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN
     2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN

In [37]:
stocks.reset_index()

      公司         日期     收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
0   BABA 2023-05-19  83.98  83.85  85.20  83.48  21.57 -0.0209         NaN
1   BABA 2023-05-22  86.10  85.67  87.48  85.65  15.11  0.0252         NaN
2   BABA 2023-05-23  82.88  84.16  84.97  82.70  18.26 -0.0374         NaN
3   BABA 2023-05-24  81.21  82.17  82.60  80.88  15.44 -0.0201         NaN
4   BABA 2023-05-25  79.88  80.43  80.66  79.81   4.20 -0.0164         NaN
5     IQ 2023-05-19   4.96   5.19   5.19   4.92  15.84 -0.0534         NaN
6     IQ 2023-05-22   4.92   5.07   5.27   4.91  13.76 -0.0081         NaN
7     IQ 2023-05-23   4.73   4.78   4.90   4.66  11.15 -0.0386         NaN
8     IQ 2023-05-24   4.63   4.70   4.72   4.40  14.19 -0.0211         NaN
9     IQ 2023-05-25   4.51   4.57   4.62   4.50   1.05 -0.0259         NaN
10    JD 2023-05-19  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN
11    JD 2023-05-22  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
12    JD 2023-05-23  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
13    JD 2023-05-24  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
14    JD 2023-05-25  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN