## 数据转换函数map、apply、applymap

1、map:只用于Series,实现每个值->值的映射;\
2、apply:用于Series实现每个值的处理,用于DataFrame实现某个轴的Series的处理;\
3、applymap:只能用于DataFrame,用于处理该DataFrame的每个元素;

**1、map用于Series值的转换**\
实列:将股票代码转换成中文名字.

In [2]:
import pandas as pd
stocks = pd.read_excel('./The Company Stocks.xlsx',engine='openpyxl')
stocks.head()

          日期  公司     收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8
0 2023-05-25  JD  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN
1 2023-05-24  JD  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN
2 2023-05-23  JD  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN
3 2023-05-22  JD  35.99  35.99  36.55  35.80   9.95  0.0265         NaN
4 2023-05-19  JD  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN

In [3]:
stocks['公司'].unique()

array(['JD', 'BABA', 'IQ'], dtype=object)

In [4]:
# 公司股票代码到中文的映射,注意这里是小写
dict_company_names = {
    'jd':'京东',
    'baba':'阿里巴巴',
    'iq':'爱奇艺'
}

**方法一: `Series.map(dict)`**

In [6]:
stocks['公司中文1']= stocks['公司'].str.lower().map(dict_company_names)

In [7]:
stocks.head()

          日期  公司     收盘     开盘      高      低    交易量     涨跌幅  Unnamed: 8 公司中文1
0 2023-05-25  JD  33.05  33.20  33.33  32.97   2.67 -0.0245         NaN    京东
1 2023-05-24  JD  33.88  34.38  34.68  33.51  13.92 -0.0331         NaN    京东
2 2023-05-23  JD  35.04  35.20  35.70  34.97   7.56 -0.0264         NaN    京东
3 2023-05-22  JD  35.99  35.99  36.55  35.80   9.95  0.0265         NaN    京东
4 2023-05-19  JD  35.06  35.53  35.72  34.80  11.48 -0.0207         NaN    京东

**方法二:`Series.map(function)`**\
function的参数是Series的每个元素的值

In [8]:
stocks['公司中文2'] = stocks['公司'].map(lambda x: dict_company_names[x.lower()])

In [9]:
stocks.head()

,日期,公司,收盘,开盘,高,低,交易量,涨跌幅,Unnamed: 8,公司中文1,公司中文2
0,2023-05-25,JD,33.05,33.20,33.33,32.97,2.67,-0.0245,NaN,京东,京东
1,2023-05-24,JD,33.88,34.38,34.68,33.51,13.92,-0.0331,NaN,京东,京东
2,2023-05-23,JD,35.04,35.20,35.70,34.97,7.56,-0.0264,NaN,京东,京东
3,2023-05-22,JD,35.99,35.99,36.55,35.80,9.95,0.0265,NaN,京东,京东
4,2023-05-19,JD,35.06,35.53,35.72,34.80,11.48,-0.0207,NaN,京东,京东

**2、apply用于Series和DataFrame的转换**
* `Series.apply(function)`,函数的参数是每个值
* `DataFrame.apply(function)`,函数的参数是Series

`Series.apply(function)`\
function的参数是Series的每个值

In [10]:
stocks['公司中文3'] =  stocks['公司'].apply(
    lambda x: dict_company_names[x.lower()]
)

In [11]:
stocks.head()

,日期,公司,收盘,开盘,高,低,交易量,涨跌幅,Unnamed: 8,公司中文1,公司中文2,公司中文3
0,2023-05-25,JD,33.05,33.20,33.33,32.97,2.67,-0.0245,NaN,京东,京东,京东
1,2023-05-24,JD,33.88,34.38,34.68,33.51,13.92,-0.0331,NaN,京东,京东,京东
2,2023-05-23,JD,35.04,35.20,35.70,34.97,7.56,-0.0264,NaN,京东,京东,京东
3,2023-05-22,JD,35.99,35.99,36.55,35.80,9.95,0.0265,NaN,京东,京东,京东
4,2023-05-19,JD,35.06,35.53,35.72,34.80,11.48,-0.0207,NaN,京东,京东,京东

`DataFrame.apply(function)`\
function的参数是对应轴的Seriess

In [12]:
stocks['公司中文4'] = stocks.apply(
    lambda x : dict_company_names[x['公司'].lower()],axis = 1
)

注意这个代码:\
1、apply是在stocks这个DataFrame上调用;\
2、lambda x的x是一个Series,因为指定了axis=1所以Series的key是列名,可以用x['公司']获取;

In [13]:
stocks.head()

,日期,公司,收盘,开盘,高,低,交易量,涨跌幅,Unnamed: 8,公司中文1,公司中文2,公司中文3,公司中文4
0,2023-05-25,JD,33.05,33.20,33.33,32.97,2.67,-0.0245,NaN,京东,京东,京东,京东
1,2023-05-24,JD,33.88,34.38,34.68,33.51,13.92,-0.0331,NaN,京东,京东,京东,京东
2,2023-05-23,JD,35.04,35.20,35.70,34.97,7.56,-0.0264,NaN,京东,京东,京东,京东
3,2023-05-22,JD,35.99,35.99,36.55,35.80,9.95,0.0265,NaN,京东,京东,京东,京东
4,2023-05-19,JD,35.06,35.53,35.72,34.80,11.48,-0.0207,NaN,京东,京东,京东,京东

**3、applymap用于DataFrame所有值的转换**

In [15]:
sub_df = stocks[['收盘','开盘','高','低','交易量']]

In [16]:
sub_df.head()

      收盘     开盘      高      低    交易量
0  33.05  33.20  33.33  32.97   2.67
1  33.88  34.38  34.68  33.51  13.92
2  35.04  35.20  35.70  34.97   7.56
3  35.99  35.99  36.55  35.80   9.95
4  35.06  35.53  35.72  34.80  11.48

In [17]:
# 将这些数字取整数,应用于所有元素
sub_df.applymap(lambda x: int(x))

    收盘  开盘   高   低  交易量
0   33  33  33  32    2
1   33  34  34  33   13
2   35  35  35  34    7
3   35  35  36  35    9
4   35  35  35  34   11
5   79  80  80  79    4
6   81  82  82  80   15
7   82  84  84  82   18
8   86  85  87  85   15
9   83  83  85  83   21
10   4   4   4   4    1
11   4   4   4   4   14
12   4   4   4   4   11
13   4   5   5   4   13
14   4   5   5   4   15

In [18]:
# 直接修改原df这几列
stocks.loc[:,['收盘','开盘','高','低','交易量']] = sub_df.applymap(lambda x: int(x))

In [19]:
stocks.head()

,日期,公司,收盘,开盘,高,低,交易量,涨跌幅,Unnamed: 8,公司中文1,公司中文2,公司中文3,公司中文4
0,2023-05-25,JD,33,33,33,32,2,-0.0245,NaN,京东,京东,京东,京东
1,2023-05-24,JD,33,34,34,33,13,-0.0331,NaN,京东,京东,京东,京东
2,2023-05-23,JD,35,35,35,34,7,-0.0264,NaN,京东,京东,京东,京东
3,2023-05-22,JD,35,35,36,35,9,0.0265,NaN,京东,京东,京东,京东
4,2023-05-19,JD,35,35,35,34,11,-0.0207,NaN,京东,京东,京东,京东