## 数据结构

### 1. Series
Series 是一种类似一维数组的对象、它由一组数据（不同数据类型）以及一组与之相关的数据标签（即索引）组成。

#### 1.1仅有的数据列表可产生最简单的Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
s1 = pd.Series([1,'a',5.2,7])

# 左侧为索引，右侧是数据
s1

0      1
1      a
2    5.2
3      7
dtype: object

In [3]:
# 获取索引
s1.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
# 获取数据
s1.values

array([1, 'a', 5.2, 7], dtype=object)

#### 1.2创建一个具有标签索引的Series

In [5]:
s2 = pd.Series([1,'a',5.2,3],index=['a','b','c','d'])

s2

a      1
b      a
c    5.2
d      3
dtype: object

#### 1.3用python字典创建Series

In [6]:
sdata={'Ohio':35000,'Texas':72000,'Oregon':16000,'Utah':5000}

s3 = pd.Series(sdata)

s3

Ohio      35000
Texas     72000
Oregon    16000
Utah       5000
dtype: int64

#### 1.4根据标签索引查询数据

In [7]:
s2

a      1
b      a
c    5.2
d      3
dtype: object

In [8]:
s2['a']

1

In [9]:
s2[['a','b']]##查询多值

a    1
b    a
dtype: object

# DataFrame

DataFrame 是一个表格型的数据结构
* 每列可以是不同的值类型
* 既有行索引index,也有列索引columns
* 可以被看做由Series组成的字典

In [10]:
data ={
    'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
    'year':[2000,2001,2002,2001,2002],
    'pop':[1.5,1.7,3.6,2.4,2.9]
}

df = pd.DataFrame(data)

In [11]:
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [12]:
df.dtypes

state     object
year       int64
pop      float64
dtype: object

In [13]:
df.columns

Index(['state', 'year', 'pop'], dtype='object')

In [14]:
df.index

RangeIndex(start=0, stop=5, step=1)

### 3.1 查询一列返回的是一个Series对象

In [15]:
df[['year']]

   year
0  2000
1  2001
2  2002
3  2001
4  2002

**3.2查询多列返回的是dataframe对象**

In [16]:
df[['year','pop']]

   year  pop
0  2000  1.5
1  2001  1.7
2  2002  3.6
3  2001  2.4
4  2002  2.9

**3.3查询行**

In [17]:
df.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object