## 对字符串的处理

**Pandas的字符串处理:**
* 1.使用方法:先获取Series的str属性，然后在属性上调用函数;
* 2.只能在字符串列上使用,不能在数字列上使用;
* 3.Dataframe上没有str属性和处理方法
* 4.Series.str并不是Py的原生字符串，而是自己的一套方法，不过大部分和原生很相似;

**Series.str相关网址**\
(https://pandas.pydata.org/docs/reference/series.html?highlight=string%20handling)

In [1]:
import pandas as pd

In [2]:
fpath = './beijing_tianqi_2018.csv'
df = pd.read_csv(fpath)

**1、获取Series的str属性,使用各种字符串处理函数**

In [3]:
df['bWendu'].str

In [4]:
# 字符串替换函数
df['bWendu'].str.replace("℃","")

0       3
1       2
2       2
3       0
4       3
       ..
360    -5
361    -3
362    -3
363    -2
364    -2
Name: bWendu, Length: 365, dtype: object

In [5]:
# 判断是不是数字
df['bWendu'].str.isnumeric()

0      False
1      False
2      False
3      False
4      False
       ...
360    False
361    False
362    False
363    False
364    False
Name: bWendu, Length: 365, dtype: bool

In [7]:
df['bWendu'].str.len()

0      2
1      2
2      2
3      2
4      2
      ..
360    3
361    3
362    3
363    3
364    3
Name: bWendu, Length: 365, dtype: int64

**2、使用str的startwith、contains等得到bool的Series可以做条件查询**

In [8]:
condition = df['ymd'].str.startswith('2018-03')
df[condition].head()

           ymd bWendu yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
59  2018-03-01     8℃    -3℃     多云       西南风   1-2级   46       优         1
60  2018-03-02     9℃    -1℃   晴~多云        北风   1-2级   95       良         2
61  2018-03-03    13℃     3℃   多云~阴        北风   1-2级  214    重度污染         5
62  2018-03-04     7℃    -2℃   阴~多云       东南风   1-2级  144    轻度污染         3
63  2018-03-05     8℃    -3℃      晴        南风   1-2级   94       良         2

**3、需要多次str处理的链式操作**

In [9]:
df['ymd'].str.replace('-','')##返回的是Series属性

0      20180101
1      20180102
2      20180103
3      20180104
4      20180105
         ...
360    20181227
361    20181228
362    20181229
363    20181230
364    20181231
Name: ymd, Length: 365, dtype: object

In [10]:
df['ymd'].str.replace('-','').slice(0,6)##不能直接使用slice切片操作对Series

AttributeError: 'Series' object has no attribute 'slice'

In [11]:
df['ymd'].str.replace('-','').str.slice(0,6)

0      201801
1      201801
2      201801
3      201801
4      201801
        ...
360    201812
361    201812
362    201812
363    201812
364    201812
Name: ymd, Length: 365, dtype: object

**4.使用正则表达式的处理**

In [13]:
#添加新列
def get_nianyueri (x):
    year,month,day = x['ymd'].split('-')##使用x['ymd]得到的式字符串，所以不是Series，可以使用split分割
    return f'{year}年{month}月{day}日'
df['中文日期'] = df.apply(get_nianyueri,axis=1)

In [14]:
df.head()

,ymd,bWendu,yWendu,tianqi,fengxiang,fengli,aqi,aqiInfo,aqiLevel,中文日期
0,2018-01-01,3℃,-6℃,晴~多云,东北风,1-2级,59,良,2,2018年01月01日
1,2018-01-02,2℃,-5℃,阴~多云,东北风,1-2级,49,优,1,2018年01月02日
2,2018-01-03,2℃,-5℃,多云,北风,1-2级,28,优,1,2018年01月03日
3,2018-01-04,0℃,-8℃,阴,东北风,1-2级,28,优,1,2018年01月04日
4,2018-01-05,3℃,-6℃,多云~晴,西北风,1-2级,50,优,1,2018年01月05日

怎样去除中文'年','月','日'

In [ ]:
##方法1: 链式replace
df['中文日期'].str.replace('年','').str.replace('月','').str.replace('日','')

In [15]:
#方法2: 正则表达式替换
df['中文日期'].str.replace('[年月日]','')

0      20180101
1      20180102
2      20180103
3      20180104
4      20180105
         ...
360    20181227
361    20181228
362    20181229
363    20181230
364    20181231
Name: 中文日期, Length: 365, dtype: object